# Unbinds due to quickshell

unbind = SUPER, SPACE
unbind = SUPER ALT, SPACE 
unbind = SUPER SHIFT CTRL, SPACE
unbind = ALT, PRINT 
unbind = SUPER, K
unbind = SUPER, ESCAPE   
unbind = SUPER CTRL, V
unbind = SUPER CTRL, SPACE
unbind = , XF86AudioRaiseVolume,  
unbind = , XF86AudioLowerVolume,  
unbind = , XF86AudioMute, Mute,   
unbind = , XF86AudioMicMute, Mute 
unbind = , XF86MonBrightnessUp,   
unbind = , XF86MonBrightnessDown, 
unbind = , XF86KbdBrightnessUp,   
unbind = , XF86KbdBrightnessDown, 
unbind = , XF86KbdLightOnOff,      
unbind = , XF86AudioNext,
unbind = , XF86AudioPause,
unbind = , XF86AudioPlay,
unbind = , XF86AudioPrev,
unbind = SUPER CTRL, comma

#-----------------------------------
# Quickshell binds
#-----------------------------------

bindd = SUPER SHIFT, Q, Quickshell, exec, ./.local/bin/qs.sh
bind = SUPER ALT, Space, exec, quickshell ipc call appLauncher openMenu
bind = SUPER, Space, exec, quickshell ipc call appLauncher openApps
bind = SUPER CTRL SHIFT, SPACE, exec, quickshell ipc call openThemePicker handle
bind = ALT, PRINT, exec, quickshell ipc call openScreenrecord handle
bind = SUPER, K, exec, quickshell ipc call openKeybindings handle
bind = SUPER, ESCAPE, exec, quickshell ipc call openSystem handle
bind = SUPER CTRL, V, exec, quickshell ipc call openClipboard handle
bind = SUPER CTRL, SPACE, exec, quickshell ipc call openBackgroundPicker handle
bind = SUPER CTRL, comma, exec, quickshell ipc call toggleDnd handle
bind = SUPER CTRl ALT, SPACE, exec, quickshell ipc call openSettings handle

bindel = , XF86AudioRaiseVolume,   exec, quickshell ipc call osdVolumeUp handle
bindel = , XF86AudioLowerVolume,   exec, quickshell ipc call osdVolumeDown handle
bindl  = , XF86AudioMute,          exec, quickshell ipc call osdVolumeMute handle
bindel = , XF86MonBrightnessUp,    exec, quickshell ipc call osdBrightnessUp handle
bindel = , XF86MonBrightnessDown,  exec, quickshell ipc call osdBrightnessDown handle
bindl  = , XF86AudioMicMute,       exec, quickshell ipc call osdMic handle
bindl  = , XF86AudioPlay,          exec, quickshell ipc call osdMediaPlayPause handle
bindl  = , XF86AudioNext,          exec, quickshell ipc call osdMediaNext handle
bindl  = , XF86AudioPrev,          exec, quickshell ipc call osdMediaPrev handle
